spring:
  profiles: dev
  application: 
    name: spring-cloud-dev
---
spring:
  profiles: test
  application: 
    name: spring-cloud-test
---
spring:
  profiles: prod
  application: 
    name: spring-cloud-prod