server:
  profiles:
    active:
    - dev
---
server:
  profiles: prod
  application: 
    name: server-prod
---
server:
  profiles: dev
  application:
    name: spring-cloud-dev
---
server:
  profiles: test
  application:
    name: spring-cloud-test
