server:
  port: 8201
spring:
  profiles: dev
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://e7001:7001/eureka
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://e7002:7002/eureka
---
server:
  port: 8203
spring:
  profiles: prod
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://e7003:7003/eureka